{
  "openapi": "3.0.1",
  "info": {
    "title": "Entrust Identity as a Service Issuance API",
    "description": "The Instant ID as a Service Issuance API provides functionality that allows a customer to manage printers and to use\nthose printers to print cards, encode magstrips on cards and encode chips on cards. The Issuance API is available as\nboth a swagger file which is available as a link from this document and also as SDKs that can be downloaded from the\nGetting Started section of the developer portal which is accessed from the Instant ID as a Service Admin portal.\n\nBefore usi[...]",
    "contact": {
      "name": "Entrust Identity as a Service",
      "url": "https://www.entrust.com/",
      "email": "support@entrust.com"
    },
    "version": "5.43"
  },
  "servers": [
    {
      "url": "https://customer.region.trustedauth.com"
    }
  ],
  "tags": [
    {
      "name": "Admin Auth",
      "description": "Administration authentication controllers"
    },
    {
      "name": "Printers",
      "description": "Printer controllers"
    },
    {
      "name": "PrintQueue",
      "description": "Print Queue controllers"
    },
    {
      "name": "BasicPrint",
      "description": "Issuance controllers"
    },
    {
      "name": "Tenants",
      "description": "Tenant controllers"
    },
    {
      "name": "Applications",
      "description": "Application controllers"
    },
    {
      "name": "Roles",
      "description": "Role controllers"
    },
    {
      "name": "EnrollmentOperations",
      "description": "Enrollment controllers"
    },
    {
      "name": "PrintAPI",
      "description": "Print enrollments"
    },
    {
      "name": "MobileFlashPassAPI",
      "description": "Issue Mobile Flash Pass"
    },
    {
      "name": "Webhooks",
      "description": "Webhook Controllers"
    }
  ],
  "paths": {
    "/api/web/v1/adminapi/authenticate": {
      "post": {
        "tags": [
          "Admin Auth"
        ],
        "summary": "Authenticate to an Admin API application.",
        "operationId": "authenticateAdminApiUsingPOST"
      }
    },
    "/api/web/v1/applicationinfo": {
      "get": {
        "tags": [
          "Applications"
        ],
        "summary": "List application information",
        "description": "List application information. Caller requires the APPLICATIONS:VIEW permission.",
        "operationId": "listApplicationInfoUsingGET",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/applications/adminapi": {
      "get": {
        "tags": [
          "Applications"
        ],
        "summary": "List Admin API application",
        "description": "List Admin API application. Caller requires the APPLICATIONS:VIEW permission.",
        "operationId": "listAdminApiApplicationsUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:VIEW"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Applications"
        ],
        "summary": "Create Admin API application",
        "description": "Create an Admin API application. Caller requires the APPLICATIONS:ADD permission.",
        "operationId": "createAdminApiApplicationUsingPOST",
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/applications/adminapi/regenerate/{id}": {
      "put": {
        "tags": [
          "Applications"
        ],
        "summary": "Regenerate Admin API application shared secret",
        "description": "Regenerate the shared secret for an Admin API application. Caller requires the APPLICATIONS:EDIT permission.",
        "operationId": "updateAdminApiSharedSecretUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v1/applications/adminapi/{id}": {
      "get": {
        "tags": [
          "Applications"
        ],
        "summary": "Get Admin API application",
        "description": "Get an Admin API application. Caller requires the APPLICATIONS:VIEW permission.",
        "operationId": "getAdminApiApplicationUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Applications"
        ],
        "summary": "Update Admin API application",
        "description": "Update an Admin API application. Caller requires the APPLICATIONS:EDIT permission.",
        "operationId": "updateAdminApiApplicationUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:EDIT"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Applications"
        ],
        "summary": "Remove Admin API application",
        "description": "Remove an Admin API application. Caller requires the APPLICATIONS:REMOVE permission.",
        "operationId": "removeAdminApiApplicationUsingDELETE",
        "security": [
          {
            "AdminAPIAuthentication": [
              "APPLICATIONS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/applications/templates": {
      "get": {
        "tags": [
          "Applications"
        ],
        "summary": "List application templates",
        "description": "List application templates. Caller requires the TEMPLATES:VIEW permission.",
        "operationId": "listApplicationTemplatesUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TEMPLATES:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/enrollment/api": {
      "put": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Update enrollment records. Caller requires the ENROLLMENTS:EDIT permission.",
        "operationId": "updateEnrollments",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:EDIT"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Create enrollment records. Caller requires the ENROLLMENTS:ADD permission.",
        "operationId": "createEnrollments",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:ADD"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Delete enrollment records. Caller requires the ENROLLMENTS:REMOVE permission.",
        "operationId": "deleteEnrollments",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/enrollment/api/readEnrollments": {
      "post": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Read enrollment records. Caller requires the ENROLLMENTS:VIEW permission.",
        "operationId": "readEnrollments",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Get all issued bulk mobile flash pass request(s)",
        "description": "Get all issued bulk mobile flash pass request(s). Caller requires the issuance view permission to access this resource.",
        "operationId": "getIssueMFPBulkOperationDetails",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Create bulk mobile flash pass request (Deprecated)",
        "description": "Create bulk mobile flash pass request. Caller requires the issuance add permission to access this resource.",
        "operationId": "issueMobileFlashPassBulkOperation",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass/cancel/{id}": {
      "delete": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Cancel mobile flash pass bulk operation",
        "description": "Cancel mobile flash pass bulk operation. Caller requires the issuance remove permission to access this resource.",
        "operationId": "cancelMobileFlashPassBulkOperation",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass/download/logs/{id}": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Download mobile flash pass bulk operation logs",
        "description": "Download logs for mobile flash pass bulk operation. Caller requires the issuance view permission to access this resource.",
        "operationId": "downloadMFPBulkOperationLogs",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass/downloadUri/{walletType}/{enrollmentId}": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Get mobile flash pass download URI",
        "description": "Retrieves the Mobile Flash Pass download URI for the specified wallet and enrollment. Caller requires the ISSUANCE:VIEW permission to access this resource.",
        "operationId": "getFlashPassDownloadURI",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass/downloads/apple/{enrollmentId}/{claimToken}": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Download Apple Wallet mobile flash pass.",
        "description": "Downloads a single Apple Wallet mobile flash pass. Caller requires the ISSUANCE:VIEW permission to access this resource.",
        "operationId": "downloadAppleMobileFlashPass",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass/downloads/google/{enrollmentId}/{claimToken}": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Download Google Wallet mobile flash pass.",
        "description": "Returns a single Google Wallet mobile flash pass URL for download. Caller requires the ISSUANCE:VIEW permission to access this resource.",
        "operationId": "downloadGoogleMobileFlashPass",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/mobileFlashPass/{id}": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Get mobile flash pass request details",
        "description": "Get mobile flash pass request details. Caller requires the issuance view permission to access this resource.",
        "operationId": "getMobileFlashPassRequestDetails",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/print": {
      "get": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Get all bulk print enrollments request(s)",
        "description": "Get all print enrollments request(s). Caller requires the issuance view permission to access this resource.",
        "operationId": "getPrintEnrollmentsBulkOperationDetails",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Create bulk print enrollment request",
        "description": "Create bulk print enrollment request. Caller requires the issuance add permission to access this resource.",
        "operationId": "printEnrollmentsBulkOperation",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/print/cancel/{id}": {
      "delete": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Cancel print enrollments bulk operation",
        "description": "Cancel print enrollments bulk operation. Caller requires the issuance remove permission to access this resource.",
        "operationId": "cancelPrintEnrollmentsBulkOperation",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/print/download/logs/{id}": {
      "get": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Download print enrollments bulk operation logs",
        "description": "Download logs for print enrollments bulk operation. Caller requires the issuance view permission to access this resource.",
        "operationId": "downloadPrintEnrollmentsBulkOperationLogs",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/print/resume": {
      "post": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Resume a print job after pre print operation",
        "description": "Resume printing for a print job after pre print operation. Caller requires the ISSUANCE:ADD permission to access this resource.",
        "operationId": "resumePrintJob",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/print/single": {
      "post": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Print single enrollment",
        "description": "Prints a single enrollment by Design Name or Enrollment ID. Caller requires the ISSUANCE:ADD permission to access this resource.",
        "operationId": "singleEnrollmentPrint",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/print/{id}": {
      "get": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Get print request details",
        "description": "Get print request details. Caller requires the issuance view permission to access this resource.",
        "operationId": "getPrintRequestDetails",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printcounts": {
      "get": {
        "tags": [
          "BasicPrint"
        ],
        "summary": "Get counts for different prints.",
        "operationId": "getPrintCounts",
        "security": [
          {
            "AdminAPIAuthentication": [
              "REPORTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers": {
      "get": {
        "tags": [
          "Printers"
        ],
        "summary": "Gets all printers.",
        "operationId": "readPrinters",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:VIEW"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Printers"
        ],
        "summary": "Creates a printer.",
        "operationId": "createPrinter",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers/print/{printStatusId}": {
      "get": {
        "tags": [
          "BasicPrint"
        ],
        "summary": "Retrieve print job status.",
        "operationId": "getPrintStatus",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "BasicPrint"
        ],
        "summary": "Cancel an executing print job.",
        "operationId": "cancelPrint",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:REMOVE"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "BasicPrint"
        ],
        "summary": "Updates an executing print job.",
        "operationId": "updatePrint",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers/summary": {
      "get": {
        "tags": [
          "Printers"
        ],
        "summary": "Retrieve count of registered printers",
        "operationId": "printersSummary",
        "security": [
          {
            "AdminAPIAuthentication": [
              "REPORTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers/{printerId}": {
      "get": {
        "tags": [
          "Printers"
        ],
        "summary": "Return a specified printer.",
        "operationId": "readPrinter",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Printers"
        ],
        "summary": "Update the specified printer.",
        "operationId": "replacePrinter",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:EDIT"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Printers"
        ],
        "summary": "Deletes a printer by ID.",
        "operationId": "deletePrinter",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers/{printerId}/preferences": {
      "get": {
        "tags": [
          "Printers"
        ],
        "summary": "Get the preferences for the specified printer.",
        "operationId": "readPrinterPreferences",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Printers"
        ],
        "summary": "Update the preferences for the specified printer.",
        "operationId": "replacePrinterPreferences",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers/{printerId}/print": {
      "post": {
        "tags": [
          "BasicPrint"
        ],
        "summary": "Perform basic print job.",
        "operationId": "print",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/printers/{printerId}/{tenantId}": {
      "delete": {
        "tags": [
          "Printers"
        ],
        "summary": "Deletes a lost printer by printer id and lost tenant ID.",
        "operationId": "deletePrinterWithTenantId",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/prints": {
      "get": {
        "tags": [
          "PrintQueue"
        ],
        "summary": "List all print jobs.",
        "operationId": "getPrintJobs",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/prints/paginated": {
      "post": {
        "tags": [
          "PrintQueue"
        ],
        "summary": "View print jobs in paginated form.",
        "operationId": "getPaginatedPrintJobs",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/prints/{printJobId}": {
      "get": {
        "tags": [
          "PrintQueue"
        ],
        "summary": "Get the given print job.",
        "operationId": "getPrintJob",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PrintQueue"
        ],
        "summary": "Delete the given print job.",
        "operationId": "deletePrintJob",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/prints/{printerId}/cancelAllActivePrints": {
      "post": {
        "tags": [
          "PrintQueue"
        ],
        "summary": "Cancel all active jobs for a given printer.",
        "description": "This API cancels the ongoing job on printer. This should be used if any job is stuck on printer i.e. the printer is not processing the job anymore and is stuck in busy state for more than 5 minutes.",
        "operationId": "cancelAllActivePrintJobs",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List roles",
        "description": "List all roles. Caller requires the ROLES:VIEW permission.",
        "operationId": "listSiteRolesUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ROLES:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/roles/{id}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get a role",
        "description": "Get a specified role. Caller requires the ROLES:VIEW permission.",
        "operationId": "getSiteRoleUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ROLES:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/tenants/{id}/spidentityprovider": {
      "get": {
        "tags": [
          "Tenants"
        ],
        "summary": "Get Tenant Identity Provider and Service Provider OIDC Application for Tenant Management.",
        "description": "Get Tenant Identity Provider and Service Provider OIDC Application for Tenant Management. Caller requires the SPIDENTITYPROVIDERS:VIEW permission.",
        "operationId": "getSpIdentityProviderUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "SPIDENTITYPROVIDERS:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Tenants"
        ],
        "summary": "Set Tenant Identity Provider and Service Provider OIDC Application for Tenant Management",
        "description": "Set Tenant Identity Provider and Service Provider OIDC Application for Tenant Management. Caller requires the SPIDENTITYPROVIDERS:EDIT permission.",
        "operationId": "setSpIdentityProviderUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "SPIDENTITYPROVIDERS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v1/users/{userid}/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "List all site roles assigned to user",
        "description": "List all site roles assigned to the specified user. Caller requires the USERSITEROLES:VIEW permission.",
        "operationId": "getUserRolesUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "USERSITEROLES:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v1/users/{userid}/roles/{roleid}": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get site role assigned to user",
        "description": "Get the specified site role assigned to the specified user. Caller requires the USERSITEROLES:VIEW permission.",
        "operationId": "getUserSiteRoleAssociationUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "USERSITEROLES:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Roles"
        ],
        "summary": "Set user role",
        "description": "Set the role of the given user to the given role. Caller requires the USERSITEROLES:EDIT permission.",
        "operationId": "modifyUserSiteRoleAssociationUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "USERSITEROLES:EDIT"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Delete a site role from a user",
        "description": "Delete a user's site role. Caller requires the USERSITEROLES:REMOVE permission.",
        "operationId": "deleteUserSiteRoleAssociationUsingDELETE",
        "security": [
          {
            "AdminAPIAuthentication": [
              "USERSITEROLES:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v1/webhooks": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "List webhooks",
        "description": "Return a list of webhooks. Caller is required to have WEBHOOKS:VIEW permission.",
        "operationId": "getWebhooksUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "WEBHOOKS:VIEW"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Register a webhook",
        "description": "Register a webhook with callback URL, webhook events etc. Caller is required to have WEBHOOKS:ADD permission.",
        "operationId": "createWebhookUsingPOST",
        "security": [
          {
            "AdminAPIAuthentication": [
              "WEBHOOKS:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v1/webhooks/test/{id}": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Test a webhook",
        "description": "Sends a dummy payload to the registered webhook callback URL. Use this to ensure your API is ready to start accepting webhook notifications. Caller is required to have WEBHOOKS:EDIT permission.",
        "operationId": "testWebhookUsingPOST",
        "security": [
          {
            "AdminAPIAuthentication": [
              "WEBHOOKS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v1/webhooks/{id}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Get a webhook by id",
        "description": "Get the specified webhook. Caller is required to have WEBHOOKS:VIEW permission.",
        "operationId": "readWebhookUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "WEBHOOKS:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Update a webhook",
        "description": "Update a webhook with callback URL, webhook events etc. Caller is required to have WEBHOOKS:EDIT permission.",
        "operationId": "updateWebhookUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "WEBHOOKS:EDIT"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "summary": "Delete a webhook",
        "description": "Delete a registered webhook by ID. Caller is required to have WEBHOOKS:REMOVE permission.",
        "operationId": "deleteWebhookUsingDELETE",
        "security": [
          {
            "AdminAPIAuthentication": [
              "WEBHOOKS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v2/enrollments": {
      "put": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Update Enrollments",
        "description": "Update one or more enrollments. Caller requires the ENROLLMENTS:EDIT permission.",
        "operationId": "updateEnrollmentsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:EDIT"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Delete Enrollments",
        "description": "Delete one or more enrollments. Caller requires the ENROLLMENTS:DELETE permission.",
        "operationId": "deleteEnrollmentsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:DELETE"
            ]
          }
        ]
      }
    },
    "/api/web/v2/enrollments/enrollmentDesigns": {
      "get": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Read Enrollment designs name",
        "description": "Read enrollment designs name. Caller requires the ENROLLMENTS:VIEW permission.",
        "operationId": "readEnrollmentsDesignNames",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/enrollments/read/{enrollmentDesignName}": {
      "post": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Read Enrollments",
        "description": "Read one or more enrollments. Caller requires the ENROLLMENTS:VIEW permission.",
        "operationId": "readEnrollmentsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/enrollments/{enrollmentDesignName}": {
      "post": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Create Enrollments",
        "description": "Create one or more enrollments. Caller requires the ENROLLMENTS:ADD permission.",
        "operationId": "createEnrollmentsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v2/enrollments/{id}": {
      "get": {
        "tags": [
          "EnrollmentOperations"
        ],
        "summary": "Read Enrollment",
        "description": "Read an enrollment. Caller requires the ENROLLMENTS:VIEW permission.",
        "operationId": "readEnrollmentV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ENROLLMENTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/mobileFlashPass": {
      "post": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Create bulk mobile flash pass request V2",
        "description": "Create bulk mobile flash pass request. Caller requires the ISSUANCE:ADD permission to access this resource.<br/><br/><b>Note:</b> Request body payload must not exceed 200 KB.",
        "operationId": "issueMobileFlashPassBulkOperationV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v2/mobileFlashPass/download/logs/{id}": {
      "get": {
        "tags": [
          "MobileFlashPassAPI"
        ],
        "summary": "Download mobile flash pass logs V2",
        "description": "Download logs for mobile flash pass. Produces a JSON file attachment. Caller requires the issuance view permission to access this resource.",
        "operationId": "downloadMFPLogsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/print": {
      "post": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Create bulk print enrollment request V2",
        "description": "Create bulk print enrollment request. Caller requires the ISSUANCE:ADD permission to access this resource.<br/><br/><b>Note:</b> Request body payload must not exceed 200 KB.",
        "operationId": "printEnrollmentsBulkOperationV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v2/print/download/logs/{id}": {
      "get": {
        "tags": [
          "PrintAPI"
        ],
        "summary": "Download print enrollments logs V2",
        "description": "Download logs for print enrollments. Caller requires the issuance view permission to access this resource.",
        "operationId": "downloadPrintEnrollmentsLogsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/printers": {
      "get": {
        "tags": [
          "Printers"
        ],
        "summary": "Gets all printers.",
        "operationId": "getPrinters",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/printers/{deviceId}": {
      "get": {
        "tags": [
          "Printers"
        ],
        "summary": "Return a specified printer using printer device id.",
        "operationId": "readPrinterByDeviceId",
        "security": [
          {
            "AdminAPIAuthentication": [
              "PRINTERS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v2/prints/paginated": {
      "post": {
        "tags": [
          "PrintQueue"
        ],
        "summary": "View print jobs in paginated form.",
        "operationId": "getPaginatedPrintJobsV2",
        "security": [
          {
            "AdminAPIAuthentication": [
              "ISSUANCE:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v4/async/tenants/{id}/createresult": {
      "get": {
        "tags": [
          "Tenants"
        ],
        "summary": "Get the result of an asynchronous tenant creation operation",
        "description": "Get the result of a tenant creation operation for a service provider. The results for a given operation can only be retrieved once. Caller requires the TENANTS:ADD permission from a service provider role.",
        "operationId": "getCreateTenantAsyncResultUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v4/async/tenants/{id}/createstatus": {
      "get": {
        "tags": [
          "Tenants"
        ],
        "summary": "Get the status of an asynchronous tenant creation operation",
        "description": "Get the status of a tenant creation operation for a service provider. Caller requires the TENANTS:VIEW permission from a service provider role.",
        "operationId": "getCreateTenantAsyncStatusUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants": {
      "post": {
        "tags": [
          "Tenants"
        ],
        "summary": "Create a tenant",
        "description": "Create a new tenant for a service provider. Caller requires the TENANTS:ADD permission from a service provider role.<br/>Notes on CreateTenantParms attributes: <br/><b>adminUser</b> (UserParms):<ul>    <li>The locale attribute is ignored if provided. It defaults to English for the first super administrator.</li>    <li>The status attributes is ignored if provided. It defaults to ACTIVE for the first super administrator.</li>    <li>The userId is required.</li></ul><b>admi[...]",
        "operationId": "createTenantUsingPOST",
        "deprecated": true,
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:ADD"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants/entitlements/usage": {
      "post": {
        "tags": [
          "Tenants"
        ],
        "summary": "Lists a page of entitlement usage information",
        "description": "Returns tenant usage information for the provided search parameters. Caller requires the TENANTS:VIEW permission. The following searchByAttributes are supported: <ul><li>startTime: a <b>mandatory</b> String value representing an ISO-8601 date in UTC time (e.g., 2018-08-04T18:15:30). Allowed operators are: GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL. </li><li>endTime: a String value representing an ISO-8601 date in UTC time (e.g., 2018-08-04T18:15:30[...]",
        "operationId": "getEntitlementUsageInfoUsingPOST",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants/{id}": {
      "get": {
        "tags": [
          "Tenants"
        ],
        "summary": "Get a tenant",
        "description": "Get the specified tenant for a service provider. Caller requires the TENANTS:VIEW permission from a service provider role.",
        "operationId": "getTenantUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:VIEW"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Tenants"
        ],
        "summary": "Delete a tenant",
        "description": "Delete the specified tenant for a service provider. Caller requires the TENANTS:REMOVE permission from a service provider role.",
        "operationId": "removeTenantUsingDELETE",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants/{id}/lock": {
      "put": {
        "tags": [
          "Tenants"
        ],
        "summary": "Lock a tenant",
        "description": "Lock the specified tenant for a service provider. Caller requires the TENANTS:EDIT permission from a service provider role.",
        "operationId": "lockTenantUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants/{id}/unlock": {
      "put": {
        "tags": [
          "Tenants"
        ],
        "summary": "Unlock a tenant",
        "description": "Unlock the specified tenant for a service provider. Caller requires the TENANTS:EDIT permission from a service provider role.",
        "operationId": "unlockTenantUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants/{tenantid}/entitlements": {
      "get": {
        "tags": [
          "Tenants"
        ],
        "summary": "Get entitlements for tenant",
        "description": "Get all entitlements for the specified tenant of the current service provider. Caller requires the SPENTITLEMENTS:VIEW permission from a service provider role.",
        "operationId": "getTenantEntitlementsUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "SPENTITLEMENTS:VIEW"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Tenants"
        ],
        "summary": "Set an entitlement",
        "description": "Set the entitlement for the specified tenant. Caller requires the SPENTITLEMENTS:EDIT permission from a service provider role.",
        "operationId": "setTenantEntitlementUsingPUT",
        "security": [
          {
            "AdminAPIAuthentication": [
              "SPENTITLEMENTS:EDIT"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenants/{tenantid}/entitlements/{type}": {
      "get": {
        "tags": [
          "Tenants"
        ],
        "summary": "Get an entitlement",
        "description": "Get the specified entitlement for a tenant. Caller requires the SPENTITLEMENTS:VIEW permission from a service provider role.",
        "operationId": "getTenantEntitlementUsingGET",
        "security": [
          {
            "AdminAPIAuthentication": [
              "SPENTITLEMENTS:VIEW"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Tenants"
        ],
        "summary": "Delete an entitlement",
        "description": "Delete the entitlement for the specified tenant. Caller requires the SPENTITLEMENTS:REMOVE permission from a service provider role.",
        "operationId": "deleteTenantEntitlementUsingDELETE",
        "security": [
          {
            "AdminAPIAuthentication": [
              "SPENTITLEMENTS:REMOVE"
            ]
          }
        ]
      }
    },
    "/api/web/v4/tenantspaged": {
      "post": {
        "tags": [
          "Tenants"
        ],
        "summary": "Lists a page of tenants",
        "description": "Returns tenants for the provided search parameters. Caller requires the TENANTS:VIEW permission. The following searchByAttributes are supported: <ul><li>hostname: a String up to 100 characters. Allowed operators are: EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS, STARTS_WITH, ENDS_WITH.</li><li>companyName: a String up to 100 characters. Allowed operators are: EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS, STARTS_WITH, ENDS_WITH.</li><li>contractMode: PRODUCTION, TRIAL, UNKNOWN[...]",
        "operationId": "getTenantsPageUsingPOST",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:VIEW"
            ]
          }
        ]
      }
    },
    "/api/web/v5/async/tenants": {
      "post": {
        "tags": [
          "Tenants"
        ],
        "summary": "Create a tenant asynchronously",
        "description": "<p>Create a new tenant for a service provider. Caller requires the TENANTS:ADD permission from a service provider role.</p><p>Notes on CreateTenantParms attributes: </p><b>adminUser</b> (UserParms):<ul>    <li>The locale attribute is ignored if provided. It defaults to English for the first super administrator.</li>    <li>The status attributes is ignored if provided. It defaults to ACTIVE for the first super administrator.</li>    <li>The userId is required.</li></ul><b>[...]",
        "operationId": "createTenantAsyncUsingPOST",
        "security": [
          {
            "AdminAPIAuthentication": [
              "TENANTS:ADD"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AdminAPIAuthentication": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}